DROP TABLE IF EXISTS CANCION;
DROP TABLE IF EXISTS LISTA_REPRODUCCION;
DROP TABLE IF EXISTS CANCION_LISTA;
CREATE TABLE CANCION(ID_CANCION INTEGER(11) PRIMARY KEY auto_increment, TITULO VARCHAR(30) NOT NULL, ARTISTA VARCHAR(30) NOT NULL, ALBUM VARCHAR(30) NOT NULL,ANNO VARCHAR(30) NOT NULL, GENERO VARCHAR NOT NULL);
CREATE TABLE LISTA_REPRODUCCION(ID_LISTA_REPRODUCCION INTEGER(11) PRIMARY KEY AUTO_INCREMENT,NOMBRE VARCHAR(30) NOT NULL, DESCRIPCION VARCHAR(30) NOT NULL);
CREATE TABLE CANCION_LISTA(ID_CANCION_LISTA INTEGER(11) PRIMARY KEY AUTO_INCREMENT,ID_CANCION INTEGER(11) NOT NULL, ID_LISTA_REPRODUCCION INTEGER(11) NOT NULL);
